---
apiVersion: v1
kind: Service
metadata:
  name: jenkins21
  labels:
    app: jenkins
spec:
  ports:
    - port: 9999
  selector:
    app: jenkins21
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins21
  labels:
    app: jenkins21
spec:
  selector:
    matchLabels:
      app: jenkins21
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins21
    spec:
      containers:
        - image: avrelian1995/avrelian_1995:latest
          name: jenkins21
          env:
          ports:
            - containerPort: 9999
              name: jenkins21